#!/bin/bash
# Demo Script - Shows what speculative decoding can do
# This is a safe demo that doesn't start a server, just shows the setup

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  SPECULATIVE DECODING - COMPLETE SETUP DEMO                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}What is Speculative Decoding?${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "A technique that speeds up inference by 1.5-3x with NO quality loss!"
echo ""
echo "How it works:"
echo "  1. Fast draft model generates N tokens quickly"
echo "  2. Main model verifies all tokens in parallel"
echo "  3. Accepted tokens are used, rejected ones regenerated"
echo "  4. Result: Much faster, identical quality"
echo ""

echo -e "${BLUE}Performance Comparison${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "%-30s %15s %12s\n" "Configuration" "Tokens/sec" "Speedup"
printf "%-30s %15s %12s\n" "────────────────────────────" "──────────────" "───────"
printf "%-30s %15s %12s\n" "Without speculative" "25-35" "1.0x"
printf "%-30s %15s %12s\n" "Fast (3 draft tokens)" "40-50" "~1.5x"
printf "%-30s %15s %12s\n" "Balanced (5 draft tokens)" "50-60" "~2.0x"
printf "%-30s %15s %12s\n" "Max (7 draft tokens)" "60-70+" "~2.5x"
echo ""

echo -e "${BLUE}Models Configured${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Main Model:  Josiefied-Qwen2.5-3B-abliterated"
echo "             ├─ High quality responses"
echo "             ├─ Uncensored (abliterated)"
echo "             └─ Uses stable Qwen2.5 (no Qwen3 bugs)"
echo ""
echo "Draft Model: Josiefied-Qwen2.5-0.5B-abliterated"
echo "             ├─ Same family = high acceptance rate"
echo "             ├─ Very fast for draft generation"
echo "             └─ Abliterated for consistency"
echo ""

echo -e "${BLUE}Available Presets${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. FAST (3 draft tokens)"
echo "   ./start-speculative.sh fast"
echo "   └─ Best for: Quick responses, interactive chat"
echo ""
echo "2. BALANCED (5 draft tokens) ⭐ RECOMMENDED"
echo "   ./start-speculative.sh balanced"
echo "   └─ Best for: General use, coding, most tasks"
echo ""
echo "3. MAX (7 draft tokens)"
echo "   ./start-speculative.sh max"
echo "   └─ Best for: Long generations, bulk processing"
echo ""

echo -e "${BLUE}System Prompts Available${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 presets/prompts/"
echo "   ├─ anti-refusal.txt  ⭐ Best uncensored responses"
echo "   ├─ expert.txt        💡 Expert technical answers"
echo "   └─ empty.txt         🔧 No system guidance"
echo ""

echo -e "${BLUE}Quick Commands${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Validate setup:      ./validate-setup.sh"
echo "Start server:        ./start-speculative.sh"
echo "Test performance:    ./test-speculative.sh"
echo "Stop server:         ./stop-server.sh"
echo ""

echo -e "${BLUE}OpenCode Integration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Already configured!"
echo "✓ Default: Balanced preset (optimal)"
echo "✓ Three variants available"
echo ""
echo "Just start the server and OpenCode will use it automatically."
echo ""

echo -e "${BLUE}What's Included${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ 3 optimized preset scripts (fast, balanced, max)"
echo "✓ 3 system prompt presets (anti-refusal, expert, empty)"
echo "✓ Main launcher with auto port fallback"
echo "✓ Performance test script"
echo "✓ Server management tools"
echo "✓ Setup validation"
echo "✓ Complete documentation"
echo "✓ OpenCode integration"
echo ""

echo -e "${BLUE}File Structure${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
tree -L 2 -F /Users/jonathanmallinger/models/presets/ 2>/dev/null || {
    echo "presets/"
    echo "├── speculative-fast.sh*"
    echo "├── speculative-balanced.sh*"
    echo "├── speculative-max.sh*"
    echo "├── README.md"
    echo "└── prompts/"
    echo "    ├── anti-refusal.txt"
    echo "    ├── expert.txt"
    echo "    └── empty.txt"
}
echo ""

echo -e "${BLUE}Next Steps${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}1. Validate everything is set up correctly:${NC}"
echo "   ./validate-setup.sh"
echo ""
echo -e "${GREEN}2. Start the server (recommended preset):${NC}"
echo "   ./start-speculative.sh"
echo ""
echo -e "${GREEN}3. In another terminal, test it:${NC}"
echo "   ./test-speculative.sh"
echo ""
echo -e "${GREEN}4. Use with OpenCode or direct API:${NC}"
echo "   # OpenCode - it's already configured!"
echo "   # Direct API - http://localhost:8000/v1"
echo ""
echo -e "${GREEN}5. When done, stop the server:${NC}"
echo "   ./stop-server.sh"
echo ""

echo -e "${BLUE}Documentation${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "QUICK_START_SPECULATIVE.md         - Detailed quick-start guide"
echo "SPECULATIVE_SETUP_COMPLETE.md      - Setup summary"
echo "SPECULATIVE_DECODING_OVERVIEW.md   - Complete overview"
echo "presets/README.md                  - Preset documentation"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Ready to go! Run ./start-speculative.sh to begin          ║"
echo "╚════════════════════════════════════════════════════════════╝"
